// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteActorProtocol.proto

package com.vasilrem.remote.protocol;

public final class RemoteActorProtocol {
  private RemoteActorProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class NodeProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use NodeProtocol.newBuilder() to construct.
    private NodeProtocol() {
      initFields();
    }
    private NodeProtocol(boolean noInit) {}
    
    private static final NodeProtocol defaultInstance;
    public static NodeProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public NodeProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_NodeProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_NodeProtocol_fieldAccessorTable;
    }
    
    // required string host = 1;
    public static final int HOST_FIELD_NUMBER = 1;
    private boolean hasHost;
    private java.lang.String host_ = "";
    public boolean hasHost() { return hasHost; }
    public java.lang.String getHost() { return host_; }
    
    // required string port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private boolean hasPort;
    private java.lang.String port_ = "";
    public boolean hasPort() { return hasPort; }
    public java.lang.String getPort() { return port_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasHost) return false;
      if (!hasPort) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasHost()) {
        output.writeString(1, getHost());
      }
      if (hasPort()) {
        output.writeString(2, getPort());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasHost()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getHost());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPort());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol result;
      
      // Construct using com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol();
        return builder;
      }
      
      protected com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDescriptor();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol getDefaultInstanceForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol) {
          return mergeFrom((com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol other) {
        if (other == com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDefaultInstance()) return this;
        if (other.hasHost()) {
          setHost(other.getHost());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setHost(input.readString());
              break;
            }
            case 18: {
              setPort(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string host = 1;
      public boolean hasHost() {
        return result.hasHost();
      }
      public java.lang.String getHost() {
        return result.getHost();
      }
      public Builder setHost(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHost = true;
        result.host_ = value;
        return this;
      }
      public Builder clearHost() {
        result.hasHost = false;
        result.host_ = getDefaultInstance().getHost();
        return this;
      }
      
      // required string port = 2;
      public boolean hasPort() {
        return result.hasPort();
      }
      public java.lang.String getPort() {
        return result.getPort();
      }
      public Builder setPort(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = getDefaultInstance().getPort();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:NodeProtocol)
    }
    
    static {
      defaultInstance = new NodeProtocol(true);
      com.vasilrem.remote.protocol.RemoteActorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NodeProtocol)
  }
  
  public static final class LocatorProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use LocatorProtocol.newBuilder() to construct.
    private LocatorProtocol() {
      initFields();
    }
    private LocatorProtocol(boolean noInit) {}
    
    private static final LocatorProtocol defaultInstance;
    public static LocatorProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocatorProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_LocatorProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_LocatorProtocol_fieldAccessorTable;
    }
    
    // required .NodeProtocol node = 1;
    public static final int NODE_FIELD_NUMBER = 1;
    private boolean hasNode;
    private com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol node_;
    public boolean hasNode() { return hasNode; }
    public com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol getNode() { return node_; }
    
    // required string serviceName = 2;
    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private boolean hasServiceName;
    private java.lang.String serviceName_ = "";
    public boolean hasServiceName() { return hasServiceName; }
    public java.lang.String getServiceName() { return serviceName_; }
    
    private void initFields() {
      node_ = com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasNode) return false;
      if (!hasServiceName) return false;
      if (!getNode().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasNode()) {
        output.writeMessage(1, getNode());
      }
      if (hasServiceName()) {
        output.writeString(2, getServiceName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNode());
      }
      if (hasServiceName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getServiceName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol result;
      
      // Construct using com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol();
        return builder;
      }
      
      protected com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDescriptor();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol getDefaultInstanceForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol) {
          return mergeFrom((com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol other) {
        if (other == com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasServiceName()) {
          setServiceName(other.getServiceName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.Builder subBuilder = com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.newBuilder();
              if (hasNode()) {
                subBuilder.mergeFrom(getNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNode(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setServiceName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .NodeProtocol node = 1;
      public boolean hasNode() {
        return result.hasNode();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol getNode() {
        return result.getNode();
      }
      public Builder setNode(com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNode = true;
        result.node_ = value;
        return this;
      }
      public Builder setNode(com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.Builder builderForValue) {
        result.hasNode = true;
        result.node_ = builderForValue.build();
        return this;
      }
      public Builder mergeNode(com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol value) {
        if (result.hasNode() &&
            result.node_ != com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDefaultInstance()) {
          result.node_ =
            com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.newBuilder(result.node_).mergeFrom(value).buildPartial();
        } else {
          result.node_ = value;
        }
        result.hasNode = true;
        return this;
      }
      public Builder clearNode() {
        result.hasNode = false;
        result.node_ = com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.getDefaultInstance();
        return this;
      }
      
      // required string serviceName = 2;
      public boolean hasServiceName() {
        return result.hasServiceName();
      }
      public java.lang.String getServiceName() {
        return result.getServiceName();
      }
      public Builder setServiceName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceName = true;
        result.serviceName_ = value;
        return this;
      }
      public Builder clearServiceName() {
        result.hasServiceName = false;
        result.serviceName_ = getDefaultInstance().getServiceName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LocatorProtocol)
    }
    
    static {
      defaultInstance = new LocatorProtocol(true);
      com.vasilrem.remote.protocol.RemoteActorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LocatorProtocol)
  }
  
  public static final class NameSendProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use NameSendProtocol.newBuilder() to construct.
    private NameSendProtocol() {
      initFields();
    }
    private NameSendProtocol(boolean noInit) {}
    
    private static final NameSendProtocol defaultInstance;
    public static NameSendProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public NameSendProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_NameSendProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_NameSendProtocol_fieldAccessorTable;
    }
    
    // required .LocatorProtocol sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private boolean hasSender;
    private com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol sender_;
    public boolean hasSender() { return hasSender; }
    public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol getSender() { return sender_; }
    
    // required .LocatorProtocol receiver = 2;
    public static final int RECEIVER_FIELD_NUMBER = 2;
    private boolean hasReceiver;
    private com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol receiver_;
    public boolean hasReceiver() { return hasReceiver; }
    public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol getReceiver() { return receiver_; }
    
    // required bytes message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    private void initFields() {
      sender_ = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance();
      receiver_ = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasSender) return false;
      if (!hasReceiver) return false;
      if (!hasMessage) return false;
      if (!getSender().isInitialized()) return false;
      if (!getReceiver().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSender()) {
        output.writeMessage(1, getSender());
      }
      if (hasReceiver()) {
        output.writeMessage(2, getReceiver());
      }
      if (hasMessage()) {
        output.writeBytes(3, getMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSender());
      }
      if (hasReceiver()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReceiver());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol result;
      
      // Construct using com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol();
        return builder;
      }
      
      protected com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.getDescriptor();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol getDefaultInstanceForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol) {
          return mergeFrom((com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol other) {
        if (other == com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasReceiver()) {
          mergeReceiver(other.getReceiver());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.Builder subBuilder = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.Builder subBuilder = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.newBuilder();
              if (hasReceiver()) {
                subBuilder.mergeFrom(getReceiver());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReceiver(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setMessage(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required .LocatorProtocol sender = 1;
      public boolean hasSender() {
        return result.hasSender();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol getSender() {
        return result.getSender();
      }
      public Builder setSender(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder setSender(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.Builder builderForValue) {
        result.hasSender = true;
        result.sender_ = builderForValue.build();
        return this;
      }
      public Builder mergeSender(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol value) {
        if (result.hasSender() &&
            result.sender_ != com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance()) {
          result.sender_ =
            com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.newBuilder(result.sender_).mergeFrom(value).buildPartial();
        } else {
          result.sender_ = value;
        }
        result.hasSender = true;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance();
        return this;
      }
      
      // required .LocatorProtocol receiver = 2;
      public boolean hasReceiver() {
        return result.hasReceiver();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol getReceiver() {
        return result.getReceiver();
      }
      public Builder setReceiver(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReceiver = true;
        result.receiver_ = value;
        return this;
      }
      public Builder setReceiver(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.Builder builderForValue) {
        result.hasReceiver = true;
        result.receiver_ = builderForValue.build();
        return this;
      }
      public Builder mergeReceiver(com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol value) {
        if (result.hasReceiver() &&
            result.receiver_ != com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance()) {
          result.receiver_ =
            com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.newBuilder(result.receiver_).mergeFrom(value).buildPartial();
        } else {
          result.receiver_ = value;
        }
        result.hasReceiver = true;
        return this;
      }
      public Builder clearReceiver() {
        result.hasReceiver = false;
        result.receiver_ = com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.getDefaultInstance();
        return this;
      }
      
      // required bytes message = 3;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:NameSendProtocol)
    }
    
    static {
      defaultInstance = new NameSendProtocol(true);
      com.vasilrem.remote.protocol.RemoteActorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NameSendProtocol)
  }
  
  public static final class GenericMessageProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use GenericMessageProtocol.newBuilder() to construct.
    private GenericMessageProtocol() {
      initFields();
    }
    private GenericMessageProtocol(boolean noInit) {}
    
    private static final GenericMessageProtocol defaultInstance;
    public static GenericMessageProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public GenericMessageProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_GenericMessageProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_GenericMessageProtocol_fieldAccessorTable;
    }
    
    // required string fqcn = 1;
    public static final int FQCN_FIELD_NUMBER = 1;
    private boolean hasFqcn;
    private java.lang.String fqcn_ = "";
    public boolean hasFqcn() { return hasFqcn; }
    public java.lang.String getFqcn() { return fqcn_; }
    
    // required bytes message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFqcn) return false;
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFqcn()) {
        output.writeString(1, getFqcn());
      }
      if (hasMessage()) {
        output.writeBytes(2, getMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFqcn()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFqcn());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol result;
      
      // Construct using com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol();
        return builder;
      }
      
      protected com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.getDescriptor();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol getDefaultInstanceForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol) {
          return mergeFrom((com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol other) {
        if (other == com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.getDefaultInstance()) return this;
        if (other.hasFqcn()) {
          setFqcn(other.getFqcn());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFqcn(input.readString());
              break;
            }
            case 18: {
              setMessage(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string fqcn = 1;
      public boolean hasFqcn() {
        return result.hasFqcn();
      }
      public java.lang.String getFqcn() {
        return result.getFqcn();
      }
      public Builder setFqcn(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFqcn = true;
        result.fqcn_ = value;
        return this;
      }
      public Builder clearFqcn() {
        result.hasFqcn = false;
        result.fqcn_ = getDefaultInstance().getFqcn();
        return this;
      }
      
      // required bytes message = 2;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GenericMessageProtocol)
    }
    
    static {
      defaultInstance = new GenericMessageProtocol(true);
      com.vasilrem.remote.protocol.RemoteActorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GenericMessageProtocol)
  }
  
  public static final class StringMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use StringMessage.newBuilder() to construct.
    private StringMessage() {
      initFields();
    }
    private StringMessage(boolean noInit) {}
    
    private static final StringMessage defaultInstance;
    public static StringMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_StringMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vasilrem.remote.protocol.RemoteActorProtocol.internal_static_StringMessage_fieldAccessorTable;
    }
    
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessage()) {
        output.writeString(1, getMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage result;
      
      // Construct using com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage();
        return builder;
      }
      
      protected com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.getDescriptor();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage getDefaultInstanceForType() {
        return com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage) {
          return mergeFrom((com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage other) {
        if (other == com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setMessage(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string message = 1;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:StringMessage)
    }
    
    static {
      defaultInstance = new StringMessage(true);
      com.vasilrem.remote.protocol.RemoteActorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:StringMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NodeProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LocatorProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocatorProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NameSendProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NameSendProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GenericMessageProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GenericMessageProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StringMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031RemoteActorProtocol.proto\"*\n\014NodeProto" +
      "col\022\014\n\004host\030\001 \002(\t\022\014\n\004port\030\002 \002(\t\"C\n\017Locat" +
      "orProtocol\022\033\n\004node\030\001 \002(\0132\r.NodeProtocol\022" +
      "\023\n\013serviceName\030\002 \002(\t\"i\n\020NameSendProtocol" +
      "\022 \n\006sender\030\001 \002(\0132\020.LocatorProtocol\022\"\n\010re" +
      "ceiver\030\002 \002(\0132\020.LocatorProtocol\022\017\n\007messag" +
      "e\030\003 \002(\014\"7\n\026GenericMessageProtocol\022\014\n\004fqc" +
      "n\030\001 \002(\t\022\017\n\007message\030\002 \002(\014\" \n\rStringMessag" +
      "e\022\017\n\007message\030\001 \002(\tB \n\034com.vasilrem.remot" +
      "e.protocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NodeProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NodeProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NodeProtocol_descriptor,
              new java.lang.String[] { "Host", "Port", },
              com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.class,
              com.vasilrem.remote.protocol.RemoteActorProtocol.NodeProtocol.Builder.class);
          internal_static_LocatorProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LocatorProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LocatorProtocol_descriptor,
              new java.lang.String[] { "Node", "ServiceName", },
              com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.class,
              com.vasilrem.remote.protocol.RemoteActorProtocol.LocatorProtocol.Builder.class);
          internal_static_NameSendProtocol_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_NameSendProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NameSendProtocol_descriptor,
              new java.lang.String[] { "Sender", "Receiver", "Message", },
              com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.class,
              com.vasilrem.remote.protocol.RemoteActorProtocol.NameSendProtocol.Builder.class);
          internal_static_GenericMessageProtocol_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_GenericMessageProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GenericMessageProtocol_descriptor,
              new java.lang.String[] { "Fqcn", "Message", },
              com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.class,
              com.vasilrem.remote.protocol.RemoteActorProtocol.GenericMessageProtocol.Builder.class);
          internal_static_StringMessage_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_StringMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StringMessage_descriptor,
              new java.lang.String[] { "Message", },
              com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.class,
              com.vasilrem.remote.protocol.RemoteActorProtocol.StringMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
